export { useWeather } from './useWeather';
export type { WeatherInput, WeatherSnapshot } from './useWeather';
export { useDeviceWeather } from './useDeviceWeather';
export { useUpcomingRoundWeather } from './useUpcomingRoundWeather';
export { useFallbackCourseCoords } from './useFallbackCourseCoords';
export { weatherCodeToIcon } from './weatherCodeToIcon';
export type { WeatherIcon } from './weatherCodeToIcon';
export { useDetailedDayForecast } from './useDetailedDayForecast';
export type { Coords, DaySummary, DetailedForecast } from './useDetailedDayForecast';
export { aggregateWeatherBucket } from './aggregateWeatherBucket';
export type { BucketStats, HourlySlice } from './aggregateWeatherBucket';
