export type TabKey =
  | 'details'
  | 'scorecard'
  | 'stats'
  | 'match'
  | 'subMatches'
  | 'skins'
  | 'wolf'
  | 'payouts'
  | 'teamScores'
  | 'teams'
  | 'scrambleTeamScore'
  | 'scrambleLeaderboard'
  | 'scrambleContributions'
  | 'leaderboard';
