/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

import { argsEnhancers } from '@storybook/addon-actions/dist/preview';

import { decorators, parameters } from './preview';

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    clearDecorators();
  }
  decorators.forEach((decorator: any) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

try {
  argsEnhancers.forEach((enhancer: any) => addArgsEnhancer(enhancer));
} catch {}

const getStories = () => {
  return [
    require('../src/components/common/BottomSheet/BottomSheet.stories.tsx'),
  ];
};

configure(getStories, module, false);

export { view } from '@storybook/react-native';
