/**
 * Shared types and constants for DetailsTab sections
 */

import type { Competition, CompetitionType, HandicapSystem, Round, TeamMode, TeamWithMembers } from '@/types/database.types';
import type { CompetitionPrizePool, PrizePoolPlacement } from '@/types';
import type { MiniLeaderboardData } from '@/utils/miniLeaderboard';

// =====================================================
// PROPS TYPES
// =====================================================

export interface CompetitionInfoSectionProps {
  competition: Competition;
}

export interface MiniLeaderboardSectionProps {
  /** 3-row window for individual standings (null hides the whole section) */
  individual: MiniLeaderboardData | null;
  /** 3-row window for team standings (null hides only the team sub-section) */
  team: MiniLeaderboardData | null;
  /** Display label for the user's team (e.g. "Hawks") */
  teamName?: string;
  /** Called when a sub-section is tapped */
  onOpenLeaderboard: (view: 'individual' | 'team') => void;
}

export interface SettingsSectionProps {
  competition: Competition;
  isOrganizer: boolean;
  /**
   * True once any round has started scoring. Locks structural fields
   * (competition_type, team_mode, team_size) that would otherwise require
   * complex data migration if changed mid-competition.
   */
  hasStartedRound: boolean;
  /**
   * Actual competition teams. The Team Size row derives its value from real
   * member counts because `competition.team_size` is a static wizard field that
   * isn't updated when teams are (re)generated by count.
   */
  teams?: TeamWithMembers[];
  /** Called when the Team Size row is pressed — navigates to the Teams tab. */
  onViewTeams?: () => void;
  /** All rounds in the competition — used by the Points Config row/sheet. */
  rounds: Round[];
}

export interface PrizePoolSectionProps {
  /** Individual prize pool (null if none configured) */
  individualPool: CompetitionPrizePool | null;
  /** Individual pool placements */
  individualPlacements: PrizePoolPlacement[];
  /** Team prize pool (null if none configured) */
  teamPool: CompetitionPrizePool | null;
  /** Team pool placements */
  teamPlacements: PrizePoolPlacement[];
  /** Whether the current user is the competition organizer */
  isOrganizer: boolean;
  /** Whether either pool is locked (any round has started) */
  isLocked: boolean;
  /** Navigate to CompetitionSettings to manage pools (organizers only) */
  onManagePress?: () => void;
  /** Handler for view transactions link */
  onViewTransactionsPress?: () => void;
}

export interface EditableDetailRowProps {
  label: string;
  value: string;
  isEditable: boolean;
  onPress?: () => void;
  icon?: string;
  chip?: boolean;
  chipColor?: string;
}

// =====================================================
// LABEL HELPERS
// =====================================================

export const competitionTypeLabels: Record<CompetitionType, string> = {
  'knockout': 'Knockout',
  'event': 'Event',
};

export const competitionTypeDescriptions: Record<CompetitionType, string> = {
  'knockout': 'A bracket-style elimination competition',
  'event': 'Fixed-term competition with an end date',
};

export const handicapSystemLabels: Record<HandicapSystem, string> = {
  'honor': 'Social',
  whs: 'WHS',
  'gross-only': 'Gross',
};

export const teamModeLabels: Record<TeamMode, string> = {
  'none': 'Individual',
  'fixed': 'Fixed Teams',
  'per-round': 'Per-Round Teams',
};
